### PR TITLE
exposed clearSource for custom stream implementations

### PR DESCRIPTION
**Pull request by alligator-is**
exposes clearSource for custom unpack stream implementations.

### CODE REVIEW

**Comment by kriszyp** [comment]
Thanks for the PR!

**Comment by vladimiry** [comment]
The `unpack.d.ts` has not been updated:
```
node_modules/msgpackr/index.d.ts:1:75 - error TS2305: Module '"./unpack"' has no exported member 'clearSource'.

1 export { Unpackr, Decoder, unpack, decode, addExtension, FLOAT32_OPTIONS, clearSource } from './unpack'
```

**Comment by vladimiry** [comment]
@kriszyp thanks for the fix. Looking forward for trying new release.

**Comment by kriszyp** [comment]
Ah yes, thanks for the reminder, published in v1.3.4.

**Pull request merged**
