### PR TITLE
fix(dist): only expose dist files

### PR DESCRIPTION
**Pull request by roggervalf**
this package is pointing to the index.js that is on the root level, we should only expose the dist files, this pr tries to fix this. Also you can run npm run dry-run to see which files are going to be exposed in npm

### CODE REVIEW

**Comment by kriszyp** [comment]
Thank you for the PR. However, the dist files are just for legacy CommonJS and browser script loading. The root .js files, including /index.js are the main modules that should be used (and are referenced by the exports in the package.json) with standard ESM loading, so I think they should be included in the published package. Also, I thought the "main" property was ignored when "exports" were defined, but maybe I'm wrong, or maybe "main" is used for some (older?) web bundlers?

**Comment by roggervalf** [comment]
@kriszyp nice to know, I was creating this pr because I was getting an error in some tests that were running in node 10 when using this package, but knowing that this is on purpose I think I can point to the dist files. Thanks for the quick response. Would you like to have the dry-run script, if not I can just close this pr.

**Comment by kriszyp** [comment]
Does node 10 benefit from the `"main": "dist/index.js"` line you added? What were the errors?

**Comment by roggervalf** [comment]
node 10 was complaining about the export:
```
export { Packr, Encoder, addExtension, pack, encode, NEVER, ALWAYS, DECIMAL_ROUND, DECIMAL_FIT } from './pack.js'
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by manast** [comment]
> @kriszyp nice to know, I was creating this pr because I was getting an error in some tests that were running in node 10 when using this package, but knowing that this is on purpose I think I can point to the dist files. Thanks for the quick response. Would you like to have the dry-run script, if not I can just close this pr.

In my opinion pointing to the dist files is not the best way to solve this. The consumer of this package should not need to know that a dist folder even exists, instead the package.json should be constructed in such a way it works for all the intended platforms. If node 10 is supported  by this package then it should work as in node 12 without needing to explicitly import from the dist directory (which btw could change in the future and break packages that depends on this one).

**Comment by kriszyp** [comment]
Right, the package.json should point to the appropriate modules for the platforms, and that is what is intended with the `exports` properties. But perhaps node 10 doesn't use those; does the `"main": "dist/index.js"` line allow you to directly `require('msgpackr')` on node 10, as it works on modern Node? And I didn't think NodeJS itself supported Node 10 anymore, but if adding that line is all it takes, then will gladly do so.

**Comment by roggervalf** [comment]
Thanks guys, so I did a little research about it, we should be safe adding that line https://nodejs.org/api/packages.html#packages_main, node 10 will use it and in upper version will use the export key, since node 10 does not have export key defined

**Comment by kriszyp** [comment]
Great, thank you for the research and the PR!

**Comment by vladimiry** [comment]
Thanks for the fix. This should make my life a little easier (bundlers/webpack-aliasing configuration matter).

**Comment by manast** [comment]
Great. You are going to see a big boost of downloads for your package 🚀

**Pull request merged**
