### PR TITLE
Add int64AsType option

### PR DESCRIPTION
**Pull request by sylv**
I need int64s/uint64s as strings instead of bigints for compatibility with other libraries, which isn't something any other messagepack library can do.

### CODE REVIEW

**Comment by kriszyp** [comment]
Thank you for the PR! What do you think about doing it as:
`int64AsType?: 'number' | 'string' | 'bigint'
Do you think that would be better or worse than two flags?

**Comment by sylv** [comment]
I thought about it, but it would break compatibility with old versions in a way that might not be obvious when people update, unless `int64AsNumber` was still supported. I'm fine with either, I think this is the least impactful way to add it though.

**Comment by kriszyp** [comment]
I was thinking the constructor could have `if (options.int64AsNumber) options.int64AsType = 'number';`

**Comment by sylv** [comment]
Done. I marked `int64AsNumber` as deprecated in the types, I'm not sure if you'd rather I just remove it entirely aside from the compatibility check.

**Comment by kriszyp** [comment]
This is great, thank you!

**Pull request merged**
