### PR TITLE
"WriteAs" option to avoid recursively writing

### PR DESCRIPTION
**Pull request by molikto**
based on https://github.com/kriszyp/msgpackr/pull/91 PR

See "extended class writeAs" test for the intended usage

### CODE REVIEW

**Comment by kriszyp** [comment]
If this is indeed a hazard and/or need, perhaps it would be better to do this automatically? That is, when `extension.write.call(this, value)` returns an Array (Array.isArray) or object, directly call `packArray` or `writeObject`, without having to use `writeAs`? This might make life easier for users that aren't as savvy to what is causing infinite recursion.

**Comment by molikto** [comment]
> If this is indeed a hazard and/or need, perhaps it would be better to do this automatically? That is, when `extension.write.call(this, value)` returns an Array (Array.isArray) or object, directly call `packArray` or `writeObject`, without having to use `writeAs`? This might make life easier for users that aren't as savvy to what is causing infinite recursion.

Ok sounds good! changed to this instead

**Comment by kriszyp** [comment]
Looks great, thank you!

**Comment by kriszyp** [comment]
Published these in v1.8.1

**Pull request merged**
